### PR TITLE
ci(lint): сonfig file linting enabled

### LINKED ISSUE #56: Implement json-schemas unit testing
JSON schemas in a directory `./schemas` should be used for unit-tests of the config file. This must be implemented in the closest future.

### PR DESCRIPTION
**Pull request by tarampampam**
# Reason for This PR

- Config file linting enabled
- Schemas for the config file renamed

Closes #56

## Description of Changes

`[Author TODO: add description of changes.]`

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by tarampampam** [comment]
@48d90782 can you "lgtm" this? :)

**Review by 48d90782 — APPROVED** [review]
lgtm-ed 👍🏻

**Comment by 48d90782** [comment]
@tarampampam Update CHANGELOG please

**Comment by tarampampam** [comment]
@48d90782 done 👍

**Pull request merged**
